[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Maps/Prototype
GameDefaultMap=/Game/Maps/Prototype
GlobalDefaultGameMode=/Script/Emberwing.EmberwingGameMode

[/Script/Engine.RendererSettings]
r.DefaultFeature.MotionBlur=False
r.DefaultFeature.AmbientOcclusion=True
r.DefaultFeature.Bloom=True
; --- Correctif ecran noir Prototype : exposition et éclairage par defaut ---
r.DefaultFeature.AutoExposure=False
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=False
r.EyeAdaptationQuality=0
r.GenerateMeshDistanceFields=True
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Shadow.Virtual.Enable=1
r.Mobile.EnableMovableSpotlights=0
r.DefaultFeature.LocalExposure=False
r.SkyLight.RealTimeReflectionCapture=True
r.Lumen.DiffuseIndirect.Allow=1

[/Script/Engine.UserInterfaceSettings]
UIScaleRule=ShortestSide
ApplicationScale=1.000000

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_ThirdPerson",NewGameName="Emberwing")

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=6CC3CAEB4A4A7402C29E528FBFCA4FC7
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

